language: ruby
cache: bundler
sudo: false
rvm:
  - 2.3.0
env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  matrix:
    - "RAILS_VERSION=4.2.6"
notifications:
  irc:
    channels:
      - "irc.freenode.org#scholarsphere"
      - "irc.freenode.org#projecthydra"
    template:
      - "%{repository}//%{branch}@%{commit} by %{author}: %{message} - %{build_url}"
services:
  - redis-server
before_script:
  - jdk_switcher use oraclejdk8
