language: ruby
before_install:
  - sudo apt-get install libclamav-dev clamav-data clamav-daemon
  - sudo bash -c 'echo Eicar-Test-Signature:0:0:58354f2150254041505b345c505a58353428505e2937434329377d2445494341522d5354414e444152442d414e544956495255532d544553542d46494c452124482b482a > /var/lib/clamav/test.ndb'
rvm:
  - "2.1.0"
  - "2.0.0"
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
notifications:
  email:
    recipients:
      - "ul-dlt-hydra@lists.psu.edu"
    on_success: "change"
    on_failure: "always"
  irc:
    channels:
      - "irc.freenode.org#scholarsphere"
      - "irc.freenode.org#projecthydra"
    template:
      - "%{repository}//%{branch}@%{commit} by %{author}: %{message} - %{build_url}"
services:
  - redis-server
