source 'https://rubygems.org'

gem 'rails', '3.2.13'

gem 'sqlite3'

gem 'devise' #BL adds this later, so check to see if we can remove this
gem 'blacklight'
gem "hydra-head", "5.4.0"
gem "solrizer", "2.1.0"

gem 'sufia', :path=>'../../'
gem 'rspec-rails', :group=>:test
gem 'capybara', :group=>:test

gem 'factory_girl'

group :assets do
  gem 'coffee-rails', '~> 3.2.1'
  gem 'jquery-rails'
  gem 'sass-rails', '~> 3.2.0'
  gem 'font-awesome-sass-rails'
end
