#!/usr/bin/env ruby
require 'rails'
require ::File.join(File.dirname(Bundler.default_gemfile), 'config/environment')

options = OpenStruct.new
options.verbose = false

args = OptionParser.new do |opts|
  opts.on("-v", "--[no-]verbose", "Run verbosely") do |v|
    options.verbose = v
  end
end

begin
  args.order!
  args.parse!
rescue => error
  $stderr.puts "ERROR: #{error}\n"
  $stderr.puts args.help
  exit 1
end

if options.verbose
  $stdout.puts "running with #{options}"
  stdout_logger = Logger.new(STDOUT)
  stdout_logger.level = Logger::DEBUG
  Rails.logger.extend(ActiveSupport::Logger.broadcast(stdout_logger))
end

validator = Sufia::Migration::Validation::Service.new
validator.call

# print a little report
Sufia::Migration::Survey::Item.migration_statuses.keys.each { |st| puts "#{st}: #{Sufia::Migration::Survey::Item.send(st).count}" }
[:missing, :wrong_type].each do |status|
  puts "#{status} ids:"
  Sufia::Migration::Survey::Item.send(status).each do |obj|
    puts "  #{obj.object_id}"
  end
end
